# Generated by Django 3.2 on 2021-06-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupmembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std1', models.CharField(max_length=30)),
                ('rollnost1', models.IntegerField()),
                ('std2', models.CharField(max_length=30)),
                ('rollnost2', models.IntegerField()),
                ('std3', models.CharField(max_length=30)),
                ('rollnost3', models.IntegerField()),
            ],
        ),
    ]
