# Generated by Django 3.2 on 2021-06-10 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_groupmembers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registrationform',
        ),
    ]
