# Generated by Django 3.2 on 2021-06-10 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_delete_registrationform'),
    ]

    operations = [
        migrations.CreateModel(
            name='registrationform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=20)),
                ('cnic', models.CharField(max_length=20)),
            ],
        ),
    ]
